DATA GRADES;
INFILE "V:/SAS Programming for Business Analytics/Week7/grades.txt";
INPUT STUDENT_ID 1-4 W1 6 W2 7 W3 8 W4 9 W5 10 W6 11 W7 12 W8 13 W9 14 W10 15 W11 16 W12 17 W13 18;
ARRAY c(13) W1-W13;
TOT=0;
DO I=1 TO 13;
TOT=TOT+c(I);
END;
DROP I W1-W13;
RUN;

PROC SORT DATA=GRADES;
BY TOT;
RUN;

TITLE "PRINTING GRADES DATASET";
PROC PRINT DATA=GRADES;
RUN;

PROC UNIVARIATE DATA=GRADES;
VAR TOT;
OUTPUT OUT=GRADES_MIN_MAX MIN=GRADES_MINIMUM MAX=GRADES_MAXIMUM;
RUN;
PROC PRINT DATA=GRADES_MIN_MAX;
RUN;

PROC TRANSPOSE DATA=GRADES_MIN_MAX OUT=GRADES_TRANSPOSED;
RUN;

PROC PRINT DATA=GRADES_TRANSPOSED;
RUN;

pROC SQL;
CREATE TABLE GRADES_FINAL AS
SELECT * FROM GRADES WHERE TOT NOT IN (SELECT COL1 FROM GRADES_TRANSPOSED);
QUIT;

*APPLYING PROC UNIVARIATE ON GRADES FINAL DATASET;
PROC UNIVARIATE DATA=GRADES_FINAL;
VAR TOT;
RUN;

*PRINTING THE DETAILS OF GRADES AS PER REQUIREMENT;
TITLE "THE FINAL DATA OF GRADES AS PER REQUIREMENT";
PROC PRINT DATA=GRADES_FINAL;
VAR STUDENT_ID TOT;
RUN;
