libname thankTA2 v9 "V:/SAS Programming for Business Analytics/Week7";
DATA COLLEGE1;
SET thankTA2.college;
Options fmtsearch=(thankTA2);
PROC SORT DATA=COLLEGE1;
BY SCHOOLSIZE;
RUN;

TITLE "MEAN AND MEDIAN OF GPA AND CLASSRANK"; 
PROC MEANS DATA=COLLEGE1 MEAN MEDIAN;
VAR GPA CLASSRANK;
BY SCHOOLSIZE;
RUN;

TITLE "MEAN AND MEDIAN OF GPA AND CLASSRANK USING CLASS STATEMENT";
PROC MEANS DATA=COLLEGE1 MEAN MEDIAN;
VAR GPA CLASSRANK;
CLASS SCHOOLSIZE;
RUN;


