DATA COLLEGE3;
SET "V:/SAS Programming for Business Analytics/Week7/college.sas7bdat";
RUN;

PROC MEANS DATA = COLLEGE3 CHARTYPE;
CLASS GENDER SCHOOLSIZE;
VAR GPA CLASSRANK;
OUTPUT OUT = COLL_MEANS MEAN = N = NMISS = MIN = MAX = / AUTONAME;
RUN;

DATA 	Grand (DROP= GENDER SCHOOLSIZE)
		GENDERWISE (DROP= SCHOOLSIZE) 
		SCHOOLWISE (DROP= GENDER)
		REQUIREDMEAN;
SET COLL_MEANS;
IF 		_TYPE_ = '00' THEN OUTPUT Grand;
ELSE IF _TYPE_ = '01' THEN OUTPUT SCHOOLWISE;
ELSE IF _TYPE_ = '10' THEN OUTPUT GENDERWISE;
ELSE IF _TYPE_ = '11' THEN OUTPUT REQUIREDMEAN;
DROP _TYPE_;
RUN;

TITLE "COLLEGE MEAN";
PROC PRINT DATA=COLL_MEANS;
RUN;

TITLE "GRAND DATASET";
PROC PRINT DATA=GRAND;
RUN;
TITLE "GENDER DATA";
PROC PRINT DATA=GENDERWISE;
RUN;

tITLE "SCHOOL SIZE DATA";
PROC PRINT DATA=SCHOOLWISE;
RUN;

TITLE "RESULT MEANS";
PROC PRINT DATA=REQUIREDMEAN;
RUN;
